Skeletal muscle type ryanodine receptor is involved in calcium signaling in human B lymphocytes.
The regulation of intracellular free Ca2+ concentration ([Ca2+]i) in B cells remains poorly understood and is presently explained almost solely by inositol 1,4,5-triphosphate (IP3)-mediated Ca2+ release, followed by activation of a store-operated channel mechanism.
In fact, there are reports indicating that IP3 production does not always correlate with the magnitude of Ca2+ release.
We demonstrate here that human B cells express a ryanodine receptor (RYR) that functions as a Ca2+ release channel during the B cell antigen receptor (BCR)-stimulated Ca2+ signaling process.
Immunoblotting studies showed that both human primary CD19(+) B and DAKIKI cells express a 565-kDa immunoreactive protein that is indistinguishable in molecular size and immunoreactivity from the RYR.
Selective reverse transcription-polymerase chain reaction, restriction fragment length polymorphism, and sequencing of cloned cDNA indicated that the major isoform of the RYR expressed in primary CD19(+) B and DAKIKI cells is identical to the skeletal muscle type (RYR1).
Saturation analysis of [3H]ryanodine binding yielded Bmax = 150 fmol/mg of protein and Kd = 110 nM in DAKIKI cells.
In fluo-3-loaded CD19(+) B and DAKIKI cells, 4-chloro-m-cresol, a potent activator of Ca2+ release mediated by the ryanodine-sensitive Ca2+ release channel, induced Ca2+ release in a dose-dependent and ryanodine-sensitive fashion.
Furthermore, BCR-mediated Ca2+ release in CD19(+) B cells was significantly altered by 4-chloro-m-cresol and ryanodine.
These results indicate that RYR1 functions as a Ca2+ release channel during BCR-stimulated Ca2+ signaling and suggest that complex Ca2+ signals that control the cellular activities of B cells may be generated by cooperation of the IP3 receptor and RYR1.
