Molecular enzymology of mammalian Delta1-pyrroline-5-carboxylate synthase.
Alternative splice donor utilization generates isoforms with different sensitivity to ornithine inhibition.
Delta1-Pyrroline-5-carboxylate synthase (P5CS; EC not assigned), a mitochondrial inner membrane, ATP- and NADPH-dependent, bifunctional enzyme, catalyzes the reduction of glutamate to Delta1-pyrroline-5-carboxylate, a critical step in the de novo biosynthesis of proline and ornithine.
We utilized published plant P5CS sequence to search the expressed sequence tag data base and cloned two full-length human P5CS cDNAs differing in length by 6 base pairs (bp) in the open reading frame.
The short cDNA has a 2379-bp open reading frame encoding a protein of 793 residues; the long cDNA, generated by "exon sliding," a form of alternative splicing, contains an additional 6-bp insert following bp +711 of the short form resulting in inclusion of two additional amino acids in the region predicted to be the gamma-glutamyl kinase active site of P5CS.
The long form predominates in all tissues examined except gut.
We also isolated the corresponding long and short murine P5CS transcripts.
To confirm the identity of the putative P5CS cDNAs, we expressed both human forms in gamma-glutamyl kinase- and gamma-glutamyl phosphate reductase-deficient strains of Saccharomyces cerevisiae and showed that they conferred the proline prototrophy.
Additionally, we found expression of the murine putative P5CS cDNAs conferred proline prototrophy to P5CS-deficient Chinese hamster ovary cells (CHO-K1).
We utilized stable CHO-K1 cell transformants to compare the biochemical characteristics of the long and short murine P5CS isoforms.
We found that both confer P5CS activity and that the short isoform is inhibited by L-ornithine with a Ki of approximately 0.25 mM.
Surprisingly, the long isoform is insensitive to ornithine inhibition.
Thus, the two amino acid insert in the long isoform abolishes feedback inhibition of P5CS activity by L-ornithine.
